### ISSUE TITLE
Windows10 Py2.7 simple test

### ISSUE THREAD

**Issue by brettbrocato** [panoplyio/panoply-python-sdk#12]
This did not work for me.  I've given Panoply about 20 minutes for the data to show up, nothing yet.  I am running the file containing this code from an Anaconda prompt in a fresh Py2.7 environment.   Fixing dependencies did not make my data transmit to Panoply.  I also tried creating the table in Panoply ahead of time.

```
# -*- coding: utf-8 -*-
"""
Spyder Editor

"""

import panoply
conn = panoply.SDK( "panoply/keykey...key", "secret...secret" )
conn.write( "tablename0", { "foo": "bar" } )
```

________________________________________
due to the warnings below, I added `import setuptools` to the beginning of setup.py . Should I put in a pull request to this effect?

The installation finished up with:
`Installed e:\anaconda3\envs\py27_panop\lib\site-packages\httplib2-0.12.0-py2.7.egg
Searching for six==1.12.0
Best match: six 1.12.0
Adding six 1.12.0 to easy-install.pth file

Using e:\anaconda3\envs\py27_panop\lib\site-packages
Finished processing dependencies for panoply-python-sdk==1.6.0`
___________________________________________________________________________________
With setup.py provided, I received these warnings:
`
python setup.py install
E:\Anaconda3\envs\py27_panop\lib\distutils\dist.py:267: UserWarning: Unknown distribution option: 'extras_require'
  warnings.warn(msg)
E:\Anaconda3\envs\py27_panop\lib\distutils\dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
running install_lib
running install_egg_info
Removing ...\py27_panop\Lib\site-packages\panoply_python_sdk-1.6.0-py2.7.egg-info
Writing ...\py27_panop\Lib\site-packages\panoply_python_sdk-1.6.0-py2.7.egg-info`

**Comment by brettbrocato** [comment]
https://community.panoply.io/t/my-panoply-python-sdk-github-issue/311/3

**Comment by brettbrocato** [comment]
@alonbrody , I'm up and running - thanks again.  Would you consider:

- [ ] adding a note on Sleep to Usage in readme?
- [ ] would you support a pull request for < import setuptools > ?

**Comment by kensaggy** [comment]
Hi @brettbrocato , thanks for reporting the issue.
We would definitely consider accepting Pull requests :)
However, given your request is so small - I've already went ahead and open a PR with these changes.. you're welcome to review and comment.

We'll run our normal internal review and testing process and then merge this.
