### ISSUE TITLE
Support Python 3

### ISSUE THREAD

**Issue by AzMoo** [panoplyio/panoply-python-sdk#16]
`execfile` was removed in python 3 and as such the `setup.py` won't run.

https://github.com/panoplyio/panoply-python-sdk/blob/95fdc2fc386581df5cd5103683f69caa2939c97b/setup.py#L6

This can be easily fixed by changing this line to:

`exec(open("panoply/constants.py").read())`

I'm not sure if this is the only thing required to support python 3 because I haven't delved far into it, but if you're open to receiving a PR I'd be happy to explore it a bit further.

**Comment by techadminRumbleon** [comment]
Do we have a fix this yet?

**Comment by ChandraSekharBellamkonda** [comment]
Do we have a proper support for python 3 available now?

**Comment by dhahn** [comment]
@AzMoo and @ChandraSekharBellamkonda I pushed a PR up for this. Could use some eyes on it to cover paths I missed: https://github.com/panoplyio/panoply-python-sdk/pull/17

**Comment by vlad-panoply** [comment]
Hello guys, I'm closing this since we have released version 2.0.0 that supports python3
